swagger: "2.0"
info:
  version: "1.0.0"
  title: "node-rest-api-boilerplate"
  description: "API REST created with Node.js and Express."
host: localhost
basePath: "/"
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      tags:
        - Example
      summary: "Endpoint to get active users"
      description: Update this spec with the correct information required.
      responses:
        200:
          $ref: "#/responses/success"
responses:
  success:
    description: OK
    schema:
      $ref: '#/definitions/User'
definitions:
  User:
    type: object
    
